#!/bin/sh

# Order the list below to select your preferred desktop environment:
DE="lxde xfce4 startx"

# Uncomment the following line if you are having issues:
#export XKL_XMODMAP_DISABLE=1

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

xsetroot -solid grey
vncconfig -nowin & # required for proper copy-paste behavior

for env in $DE ; do
    if [ -x "$(command -v $env)" ] ; then exec "$env"
    elif [ -x "$(command -v /usr/bin/start$env)" ] ; then exec "/usr/bin/start$env"
    else echo "Could not find $env"
    fi
done


# If you want to load the default environment, use this:
#unset SESSION_MANAGER
#unset DBUS_SESSION_BUS_ADDRESS
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
#exec /etc/X11/xinit/xinitrc

# If you want to load the full Gnome environment, add this:
#gnome-terminal &
#gnome-session &
#gnome-panel &
#gnome-settings-daemon &


# Fallback: Standard X utilities
uxterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
exec /etc/X11/Xsession

